// MoloAirSite/src/app/booking/booking.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { ActivatedRoute, Router } from '@angular/router';
import { Customer } from '../models/Customer';
import { NewBookingRequest } from '../models/NewBookingRequest';
import { BookingService } from '../services/Booking/booking.service';
import { CustomerService } from '../services/Customer/customer.service';
import { FlightService } from '../services/Flight/flight.service';
import { SuccessDialogComponent } from '../success-dialog/success-dialog.component';

@Component({
  selector: 'app-booking',
  templateUrl: './booking.component.html',
  styleUrls: ['./booking.component.css']
})
export class BookingComponent implements OnInit {

  bookingMade = false;

  customer: Customer | undefined;
  customerId: Number = 0;
  username: String = '';
  firstName: String = '';
  lastName: String = '';
  passportNumber: String = '';
  email: String = '';
  phoneNumber: String = '';

  bookingId: Number = 0;
  referenceNumber: String = '';

  flightId: Number = 0;
  flightNumber: String = '';
  origin: String = '';
  destination: String = '';
  departureTime: Date = new Date();
  arrivalTime: Date = new Date();
  seatsAvailable: Number = 0;
  seatCost: Number = 0;

  constructor(private dialog: MatDialog,private route: ActivatedRoute, private flightService: FlightService, private customerService: CustomerService, private bookingService: BookingService, private router: Router) { }

  /*
  - after all these stuff, make customer profile page
  - show customer bookings
  - fix flight search feature
  - sleep - we dont do that :(

  
  */

  myForm = new FormGroup({
    myNumber: new FormControl(1)
  });

  ngOnInit(): void {
    this.route.queryParams.subscribe(params => {
      this.customerId = params['customerId'];
      this.flightId = params['flightId'];
    });
    this.getflightDetails();
    this.getCustomerDetails();

    
    
  }

  getflightDetails() {
    this.flightService.getFlightById(this.flightId).subscribe(
      (response) => {
        if(response.body != null) {
          this.flightNumber = response.body.flightNumber;
          this.origin = response.body.origin;
          this.destination = response.body.destination;
          this.departureTime = response.body.departureTime;
          this.arrivalTime = response.body.arrivalTime;
          this.seatsAvailable = response.body.seatsAvailable;
          this.seatCost = response.body.seatCost; 
        }
      }
    );
  }

  getCustomerDetails() {
    this.customerService.getCustomerById(this.customerId).subscribe(
      (response) => {
        if(response.body != null) {
          this.username = response.body.username;
          this.firstName = response.body.firstName;
          this.lastName = response.body.lastName;
          this.passportNumber = response.body.passportNumber;
          this.email = response.body.email;
          this.phoneNumber = response.body.phoneNumber;

          this.customer = new Customer(this.customerId, this.username, this.firstName, this.lastName, this.passportNumber, this.email, this.phoneNumber);
        }
      }
    );
  }

  makeBooking() {
    if(this.bookingMade == false)
    {
      const newBookingRequest = new NewBookingRequest(this.customerId, this.flightId);

      this.bookingService.createBooking(newBookingRequest).subscribe(
        (response) => {
          if(response.body != null) {
            this.bookingId = response.body.bookingId;
            this.referenceNumber = response.body.referenceNumber;

            let dialogRef = this.dialog.open(SuccessDialogComponent);

            dialogRef.afterClosed().subscribe(result => {
              console.log(`Dialog result: ${result}`);
              this.bookingMade = true;
            });
          }
        }
      );
    }
    else
    {
      this.router.navigate(['/profile'], { queryParams: { customer: JSON.stringify(this.customer) }})
    }
  }

  seatPrice(): any {
    if(this.myForm.value.myNumber != null){
      return this.myForm.value.myNumber * this.seatCost.valueOf();
    }
  }
}

<body>
  <mat-card class="bigCard">
    <mat-card-header>
      <mat-card-title>{{bookingMade ? "View Booking" : "Finalize your Booking"}}</mat-card-title>
    </mat-card-header>
    <div class="cards">
      <mat-card class="customerCard">
        <mat-card-title>Customer Details</mat-card-title>
        <mat-card-subtitle><strong>CustomerID: </strong>{{customerId}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Username: </strong>{{username}}</mat-card-subtitle>
        <mat-card-subtitle><strong>FirstName: </strong>{{firstName}}</mat-card-subtitle>
        <mat-card-subtitle><strong>LastName: </strong>{{lastName}}</mat-card-subtitle>
        <mat-card-subtitle><strong>PassportNumber: </strong>{{passportNumber}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Email: </strong>{{email}}</mat-card-subtitle>
        <mat-card-subtitle><strong>PhoneNumber: </strong>{{phoneNumber}}</mat-card-subtitle>
      </mat-card>
      
      <mat-card class="flightCard">
        <mat-card-title>Flight Details</mat-card-title>
        <mat-card-subtitle><strong>FlightID: </strong>{{flightId}}</mat-card-subtitle>
        <mat-card-subtitle><strong>FlightNumber: </strong>{{flightNumber}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Origin: </strong>{{origin}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Destination: </strong>{{destination}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Departure Time: </strong>{{departureTime | date:'MMM d, y h:mm a'}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Arrival Time: </strong>{{arrivalTime | date:'MMM d, y h:mm a'}}</mat-card-subtitle>
        <mat-card-subtitle><strong>Seats Available: </strong>{{seatsAvailable}}</mat-card-subtitle>
        <mat-card-subtitle>
          <strong>Number of Seats to purchase: </strong>
          <form [formGroup]="myForm">
              <input mat-input type="number" min="1" step="1" formControlName="myNumber">
          </form>
          </mat-card-subtitle>
        <mat-card-subtitle><strong>{{bookingMade ? "Price paid: ": "Price to pay: "}}</strong>R{{seatPrice()}}</mat-card-subtitle>
      </mat-card>
      

      <mat-card class="bookingCard" *ngIf="bookingMade">
          <mat-card-title>Booking Details</mat-card-title>
          <mat-card-subtitle><strong>BookingID: </strong> {{bookingId}}</mat-card-subtitle>
          <mat-card-subtitle><strong>CustomerID: </strong>{{customerId}}</mat-card-subtitle>
          <mat-card-subtitle><strong>FlightID: </strong>{{flightId}}</mat-card-subtitle>
          <mat-card-subtitle><strong>Reference Number: </strong>{{referenceNumber}}</mat-card-subtitle>
      </mat-card>
    </div>
      
      
      
    
    <mat-card-actions id="spaceHle">
      <button class="myBtn" mat-button (click)="makeBooking()">{{bookingMade ? "Go to profile" : "Confirm"}}</button>
      <button class="myBtn" mat-button *ngIf="bookingMade" routerLink="/">Done</button>
      <button class="myBtn" *ngIf="!bookingMade" mat-button routerLink="/flights">Cancel</button>
    </mat-card-actions>
  </mat-card>
</body>

// MoloAirSite/React version/molo-air-react/src/Booking Component/booking.js
import { Component, useEffect, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Card, Box, TextField, InputAdornment, Button } from "@mui/material";
import './booking.css';
import { makeBooking } from "../Services/bookingService";

class Booking extends Component{
render(){
    return (
            <>
                <BookingPage/>
            </>
        )
    }
}

function BookingPage(){
    const[bookingMade, setBookingMade] = useState(false);
    const[customer, setCustomer] = useState([])
    const[bookingResponse, setBookingResponse] = useState([])
    const[theFlight, setTheFlight] = useState([])
    const[theNumber, setTheNumber] = useState(1);
    const[thePrice, setThePrice] = useState(theFlight.seatCost);

    const [bookingRequest, setBookingRequest] = useState([]);
    const location = useLocation();

    useEffect(() => {
        setBookingRequest(location.state.booking);
        setCustomer(JSON.parse(location.state.customer));
        setTheFlight(JSON.parse(location.state.flight))
    }, [location]);

    useEffect(() => {
        setThePrice(theFlight.seatCost * theNumber);
    }, [theNumber]);

    const seatPrice = e => {
        e.preventDefault();
        setTheNumber(e.target.value)
    }

    const bookFlight = async () => {
        let response = await makeBooking(bookingRequest)
        console.log(response)
        
        if(response !== null && response !== []){
            setBookingMade(true);
            setBookingResponse(response)
        } else {
            alert("something went wrong")
        }
        
    }


    return (
        <>
            <Box display="flex" justifyContent="center" alignItems="center" height="100%">
                <Card className="bigCard">
                    {bookingMade ? "View Booking" : "Finalize your Booking"}
                    <Box className="cardsContainer">
                        <Card className="customerCard">
                            <h2>Customer Details</h2>
                            <p><strong>CustomerID: </strong>{customer.id}</p>
                            <p><strong>Username: </strong>{customer.username}</p>
                            <p><strong>FirstName: </strong>{customer.firstName}</p>
                            <p><strong>LastName: </strong>{customer.lastName}</p>
                            <p><strong>PassportNumber: </strong>{customer.passportNumber}</p>
                            <p><strong>Email: </strong>{customer.email}</p>
                            <p><strong>PhoneNumber: </strong>{customer.phoneNumber}</p>
                        </Card>
                        <Card className="flightCard">
                            <h2>Flight Details</h2>
                            <p><strong>FlightID: </strong>{theFlight.id}</p>
                            <p><strong>FlightNumber: </strong>{theFlight.flightNumber}</p>
                            <p><strong>Origin: </strong>{theFlight.origin}</p>
                            <p><strong>Destination: </strong>{theFlight.destination}</p>
                            <p><strong>Departure Time: </strong>{formatMyDate(theFlight.departureTime)}</p>
                            <p><strong>Arrival Time: </strong>{formatMyDate(theFlight.arrivalTime)}</p>
                            <p><strong>Seats Available: </strong>{theFlight.seatsAvailable}</p>
                            <p><strong>Number of Seats to purchase: </strong></p>
                            {!bookingMade ? (
                                <form>
                                <input type="number" min="1" step="1" onChange={seatPrice} value={theNumber}/>
                                </form>
                            ) : <div></div>}
                            
                            <p><strong>{bookingMade ? "Price paid: ": "Price to pay: "}</strong>R{thePrice}</p>
                        </Card>
                        {bookingMade ? (
                            <Card className="bookingCard">
                                <h2>Booking Details</h2>
                                <p><strong>BookingID: </strong>{bookingResponse.bookingId}</p>
                                <p><strong>CustomerID: </strong>{bookingResponse.customerId}</p>
                                <p><strong>FlightID: </strong>{bookingResponse.flightId}</p>
                                <p><strong>Reference Number: </strong>{bookingResponse.referenceNumber}</p>
                            </Card>
                        ) : <div></div>}
                        <Button class="myBtn" onClick={bookFlight}>{bookingMade ? "Go to profile" : "Confirm"}</Button>
                    </Box>
                    
                    
                </Card>
            </Box>
        </>
    )
}

function formatMyDate(dateTimeString){
    const formattedDate = new Date(dateTimeString).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    });
    const formattedTime = new Date(dateTimeString).toLocaleDateString('en-US', {
        hour: 'numeric',
        minute: 'numeric',
        hour12: true,
    });
    const formatted = formattedDate + ' ' + formattedTime;
    return formatted;
}


export default Booking;
